set(groot,'defaultAxesBox','on');
set(groot, 'defaultAxesColorOrder', [0, 0, 0]);
set(groot, 'defaultLineLineWidth', 1);
set(groot,'defaultAxesColor',[1,1,1]);
set(groot,'defaultAxesNextPlot','add');
set(groot,'defaultAxesTickLabelInterpreter','latex');
set(groot,'defaultAxesXGrid','on');
set(groot,'defaultAxesYGrid','on');
set(groot,'defaultAxesZGrid','on');
set(groot, 'defaultAxesLineWidth', 1.5);
set(groot,'defaultAxesLabelFontSizeMultiplier',1.25);
set(groot,'defaultLegendInterpreter','latex');
set(groot,'defaultFigureColor',[1,1,1]);
set(groot,'defaultFigureMenuBar','figure');
set(groot,'defaultFigureNumberTitle','off');
set(groot,'defaultFigureWindowState','normal');
set(groot,'defaultTextInterpreter','latex');
set(groot,'defaultTiledLayoutPadding','compact');
set(groot,'defaultTiledLayoutTileSpacing','compact');