/* This file was automatically generated by CasADi 3.6.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) treeDyn_mex_ ## ID
#endif

#include <math.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[44] = {40, 1, 0, 40, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39};

/* xdot:(i0[8],i1[40])->(o0[8]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a107, a108, a109, a11, a110, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a1=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][1]=a1;
  a2=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][2]=a2;
  a3=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][3]=a3;
  a4=1.;
  a5=-5.;
  a6=arg[0]? arg[0][2] : 0;
  a7=cos(a6);
  a8=sin(a6);
  a9=(a7+a8);
  a10=(a5*a9);
  a11=10.;
  a12=(a8-a7);
  a13=(a11*a12);
  a10=(a10-a13);
  a13=-30.;
  a10=(a10+a13);
  a13=30.;
  a10=(a10/a13);
  a14=arg[0]? arg[0][0] : 0;
  a15=cos(a14);
  a16=cos(a6);
  a17=(a15*a16);
  a18=sin(a14);
  a19=sin(a6);
  a20=(a18*a19);
  a17=(a17-a20);
  a20=2.;
  a21=(a15*a19);
  a22=(a18*a16);
  a21=(a21+a22);
  a22=(a20*a21);
  a22=(a17+a22);
  a23=(a10*a22);
  a24=-1.;
  a25=(a15*a19);
  a26=(a18*a16);
  a25=(a25+a26);
  a26=(a15+a18);
  a27=(a25*a26);
  a28=(a15*a16);
  a29=(a18*a19);
  a28=(a28-a29);
  a29=(a15-a18);
  a30=(a28*a29);
  a27=(a27+a30);
  a27=(a24-a27);
  a30=(a17*a27);
  a31=(a15*a16);
  a32=(a18*a19);
  a31=(a31-a32);
  a32=(a31*a26);
  a33=(a18*a16);
  a34=(a15*a19);
  a33=(a33+a34);
  a34=(a33*a29);
  a32=(a32-a34);
  a32=(a20-a32);
  a34=(a21*a32);
  a30=(a30-a34);
  a23=(a23-a30);
  a34=15.;
  a35=1.6666666666666670e+00;
  a36=(a35*a12);
  a37=1.6666666666666665e+00;
  a38=(a37*a9);
  a36=(a36-a38);
  a38=(a36*a12);
  a39=(a37*a12);
  a40=4.1666666666666670e+00;
  a41=(a40*a9);
  a39=(a39-a41);
  a41=(a39*a9);
  a38=(a38-a41);
  a38=(a34+a38);
  a23=(a23/a38);
  a41=(a18*a16);
  a42=(a15*a19);
  a41=(a41+a42);
  a42=(a41*a27);
  a43=(a15*a16);
  a44=(a18*a19);
  a43=(a43-a44);
  a44=(a43*a32);
  a42=(a42+a44);
  a44=(a42*a23);
  a45=arg[0]? arg[0][1] : 0;
  a46=sin(a45);
  a47=arg[0]? arg[0][3] : 0;
  a48=cos(a47);
  a49=(a46*a48);
  a50=cos(a45);
  a51=sin(a47);
  a52=(a50*a51);
  a49=(a49+a52);
  a52=(a50*a51);
  a53=(a46*a48);
  a52=(a52+a53);
  a53=(a50-a46);
  a54=(a52*a53);
  a55=(a50*a48);
  a56=(a46*a51);
  a55=(a55-a56);
  a56=(a46+a50);
  a57=(a55*a56);
  a54=(a54-a57);
  a54=(a54+a24);
  a24=(a49*a54);
  a57=(a50*a48);
  a58=(a46*a51);
  a57=(a57-a58);
  a58=(a50*a48);
  a59=(a46*a51);
  a58=(a58-a59);
  a59=(a58*a53);
  a60=(a46*a48);
  a61=(a50*a51);
  a60=(a60+a61);
  a61=(a60*a56);
  a59=(a59+a61);
  a61=(a57*a59);
  a24=(a24+a61);
  a61=(a50*a48);
  a62=(a46*a51);
  a61=(a61-a62);
  a62=(a61*a54);
  a63=(a50*a51);
  a64=(a46*a48);
  a63=(a63+a64);
  a64=(a63*a59);
  a62=(a62-a64);
  a64=-10.;
  a65=sin(a47);
  a66=cos(a47);
  a67=(a65-a66);
  a68=(a5*a67);
  a68=(a64-a68);
  a68=(a68/a11);
  a69=(a68*a61);
  a69=(a62-a69);
  a70=2.5000000000000000e+00;
  a71=(a70*a67);
  a72=(a71*a67);
  a73=5.;
  a74=(a65+a66);
  a75=(a73*a74);
  a76=(a75*a74);
  a72=(a72+a76);
  a34=(a34+a72);
  a69=(a69/a34);
  a72=(a24*a69);
  a44=(a44-a72);
  a72=(a20*a43);
  a72=(a72-a41);
  a76=(a22/a13);
  a77=(a72*a76);
  a44=(a44+a77);
  a77=(a61/a11);
  a78=(a49*a77);
  a44=(a44-a78);
  a78=casadi_sq(a44);
  a10=(a10*a72);
  a10=(a42+a10);
  a10=(a10/a38);
  a79=(a42*a10);
  a68=(a68*a49);
  a68=(a24-a68);
  a68=(a68/a34);
  a80=(a24*a68);
  a79=(a79+a80);
  a80=(a72/a13);
  a81=(a72*a80);
  a79=(a79+a81);
  a81=(a49/a11);
  a82=(a49*a81);
  a79=(a79+a82);
  a82=casadi_sq(a79);
  a78=(a78+a82);
  a82=(a30*a23);
  a83=(a62*a69);
  a82=(a82-a83);
  a83=(a22*a76);
  a82=(a82-a83);
  a83=(a61*a77);
  a82=(a82-a83);
  a83=casadi_sq(a82);
  a84=(a22*a80);
  a85=(a30*a10);
  a86=(a62*a68);
  a85=(a85+a86);
  a84=(a84-a85);
  a85=(a61*a81);
  a84=(a84-a85);
  a85=casadi_sq(a84);
  a83=(a83+a85);
  a85=(a83*a78);
  a86=(a82*a44);
  a87=(a84*a79);
  a86=(a86-a87);
  a87=(a44*a82);
  a88=(a79*a84);
  a87=(a87-a88);
  a88=(a86*a87);
  a85=(a85-a88);
  a78=(a78/a85);
  a88=(a78*a82);
  a86=(a86/a85);
  a89=(a86*a44);
  a88=(a88-a89);
  a89=(a23*a88);
  a78=(a78*a84);
  a86=(a86*a79);
  a78=(a78+a86);
  a86=(a10*a78);
  a89=(a89-a86);
  a86=(a89*a30);
  a83=(a83/a85);
  a44=(a83*a44);
  a87=(a87/a85);
  a82=(a87*a82);
  a44=(a44-a82);
  a23=(a23*a44);
  a87=(a87*a84);
  a83=(a83*a79);
  a87=(a87+a83);
  a10=(a10*a87);
  a23=(a23+a10);
  a10=(a23*a42);
  a86=(a86+a10);
  a86=(a4-a86);
  a10=arg[1]? arg[1][0] : 0;
  a83=(a39*a7);
  a79=(a36*a8);
  a83=(a83-a79);
  a83=(a5+a83);
  a79=cos(a14);
  a84=arg[1]? arg[1][10] : 0;
  a82=(a79*a84);
  a85=sin(a14);
  a90=arg[1]? arg[1][11] : 0;
  a91=(a85*a90);
  a82=(a82+a91);
  a91=arg[1]? arg[1][5] : 0;
  a92=(a79*a91);
  a93=arg[1]? arg[1][4] : 0;
  a94=(a85*a93);
  a92=(a92-a94);
  a94=(a0*a92);
  a94=(a82+a94);
  a83=(a83*a94);
  a39=(a39*a8);
  a36=(a36*a7);
  a39=(a39+a36);
  a39=(a5+a39);
  a36=(a79*a90);
  a94=(a85*a84);
  a36=(a36-a94);
  a94=(a79*a93);
  a95=(a85*a91);
  a94=(a94+a95);
  a95=(a0*a94);
  a95=(a36-a95);
  a39=(a39*a95);
  a83=(a83+a39);
  a39=arg[1]? arg[1][15] : 0;
  a95=(a38*a39);
  a83=(a83+a95);
  a95=(a79*a93);
  a96=(a85*a91);
  a95=(a95+a96);
  a96=(a73*a95);
  a97=(a79*a91);
  a98=(a85*a93);
  a97=(a97-a98);
  a96=(a96*a97);
  a98=(a73*a97);
  a98=(a98*a95);
  a96=(a96-a98);
  a98=arg[1]? arg[1][7] : 0;
  a99=(a79*a98);
  a100=arg[1]? arg[1][8] : 0;
  a101=(a85*a100);
  a99=(a99+a101);
  a101=(a73*a99);
  a79=(a79*a100);
  a85=(a85*a98);
  a79=(a79-a85);
  a85=(a73*a79);
  a101=(a101-a85);
  a85=arg[1]? arg[1][6] : 0;
  a101=(a101*a85);
  a96=(a96+a101);
  a101=(a73*a99);
  a102=(a11*a79);
  a101=(a101-a102);
  a101=(a101*a99);
  a96=(a96+a101);
  a101=(a11*a99);
  a102=(a73*a79);
  a101=(a101-a102);
  a101=(a101*a79);
  a96=(a96+a101);
  a101=(a5*a95);
  a102=(a5*a97);
  a101=(a101-a102);
  a102=arg[1]? arg[1][9] : 0;
  a103=(a102+a0);
  a101=(a101*a103);
  a96=(a96+a101);
  a101=arg[1]? arg[1][21] : 0;
  a96=(a96-a101);
  a101=(a103+a2);
  a104=(a73*a101);
  a105=(a7*a95);
  a106=(a8*a97);
  a105=(a105+a106);
  a106=(a9*a103);
  a105=(a105-a106);
  a104=(a104*a105);
  a106=(a7*a99);
  a107=(a8*a79);
  a106=(a106+a107);
  a107=(a73*a106);
  a108=(a85+a99);
  a108=(a108+a79);
  a107=(a107*a108);
  a104=(a104-a107);
  a107=(a73*a106);
  a107=(a107*a106);
  a104=(a104-a107);
  a107=(a64*a106);
  a79=(a7*a79);
  a99=(a8*a99);
  a79=(a79-a99);
  a107=(a107*a79);
  a104=(a104-a107);
  a107=(a5*a101);
  a107=(a107*a101);
  a104=(a104+a107);
  a107=arg[1]? arg[1][29] : 0;
  a104=(a104-a107);
  a104=(a12*a104);
  a107=(a73*a79);
  a107=(a107*a108);
  a99=(a73*a101);
  a109=(a7*a97);
  a110=(a8*a95);
  a109=(a109-a110);
  a110=(a12*a103);
  a109=(a109+a110);
  a99=(a99*a109);
  a107=(a107-a99);
  a99=(a73*a79);
  a99=(a99*a106);
  a107=(a107+a99);
  a99=(a64*a79);
  a99=(a99*a79);
  a107=(a107+a99);
  a99=(a11*a101);
  a99=(a99*a101);
  a107=(a107-a99);
  a99=arg[1]? arg[1][28] : 0;
  a107=(a107-a99);
  a107=(a9*a107);
  a104=(a104-a107);
  a107=(a73*a105);
  a107=(a107*a109);
  a99=(a73*a109);
  a99=(a99*a105);
  a107=(a107-a99);
  a99=(a64*a106);
  a110=(a73*a79);
  a99=(a99-a110);
  a99=(a99*a108);
  a107=(a107+a99);
  a99=(a64*a106);
  a108=(a11*a79);
  a99=(a99-a108);
  a99=(a99*a106);
  a107=(a107+a99);
  a99=25.;
  a99=(a99*a106);
  a64=(a64*a79);
  a99=(a99-a64);
  a99=(a99*a79);
  a107=(a107+a99);
  a105=(a11*a105);
  a109=(a5*a109);
  a105=(a105-a109);
  a105=(a105*a101);
  a107=(a107+a105);
  a105=arg[1]? arg[1][33] : 0;
  a107=(a107-a105);
  a104=(a104+a107);
  a96=(a96+a104);
  a35=(a35*a12);
  a104=(a37*a9);
  a35=(a35-a104);
  a35=(a35*a2);
  a104=(a35*a7);
  a37=(a37*a12);
  a40=(a40*a9);
  a37=(a37-a40);
  a37=(a37*a2);
  a40=(a37*a8);
  a104=(a104+a40);
  a104=(a104*a95);
  a40=(a35*a8);
  a105=(a37*a7);
  a40=(a40-a105);
  a40=(a40*a97);
  a104=(a104+a40);
  a35=(a35*a9);
  a37=(a37*a12);
  a35=(a35+a37);
  a35=(a35*a103);
  a104=(a104-a35);
  a96=(a96-a104);
  a104=3.3333333333333333e-02;
  a35=(a104*a12);
  a35=(a11*a35);
  a104=(a104*a9);
  a104=(a5*a104);
  a35=(a35-a104);
  a35=(a35+a4);
  a104=arg[1]? arg[1][2] : 0;
  a37=(a104-a107);
  a35=(a35*a37);
  a96=(a96+a35);
  a83=(a83+a96);
  a10=(a10-a83);
  a10=(a10/a38);
  a86=(a86*a10);
  a38=(a89*a62);
  a83=(a23*a24);
  a38=(a38+a83);
  a83=arg[1]? arg[1][1] : 0;
  a96=(a71*a66);
  a35=(a75*a65);
  a96=(a96-a35);
  a96=(a5+a96);
  a35=cos(a45);
  a37=(a35*a84);
  a40=sin(a45);
  a105=(a40*a90);
  a37=(a37+a105);
  a105=(a35*a91);
  a101=(a40*a93);
  a105=(a105-a101);
  a101=(a1*a105);
  a101=(a37+a101);
  a96=(a96*a101);
  a71=(a71*a65);
  a75=(a75*a66);
  a71=(a71+a75);
  a71=(a73+a71);
  a90=(a35*a90);
  a84=(a40*a84);
  a90=(a90-a84);
  a84=(a35*a93);
  a75=(a40*a91);
  a84=(a84+a75);
  a75=(a1*a84);
  a75=(a90-a75);
  a71=(a71*a75);
  a96=(a96+a71);
  a71=(a34*a39);
  a96=(a96+a71);
  a71=(a35*a93);
  a75=(a40*a91);
  a71=(a71+a75);
  a75=(a73*a71);
  a91=(a35*a91);
  a93=(a40*a93);
  a91=(a91-a93);
  a75=(a75*a91);
  a93=(a73*a91);
  a93=(a93*a71);
  a75=(a75-a93);
  a93=(a35*a98);
  a101=(a40*a100);
  a93=(a93+a101);
  a101=(a5*a93);
  a35=(a35*a100);
  a40=(a40*a98);
  a35=(a35-a40);
  a40=(a73*a35);
  a101=(a101-a40);
  a101=(a101*a85);
  a75=(a75+a101);
  a101=(a5*a93);
  a40=(a11*a35);
  a101=(a101-a40);
  a101=(a101*a93);
  a75=(a75+a101);
  a101=(a11*a93);
  a40=(a5*a35);
  a101=(a101-a40);
  a101=(a101*a35);
  a75=(a75+a101);
  a101=(a73*a71);
  a40=(a5*a91);
  a101=(a101-a40);
  a102=(a102+a1);
  a101=(a101*a102);
  a75=(a75+a101);
  a101=arg[1]? arg[1][27] : 0;
  a75=(a75-a101);
  a101=(a66*a35);
  a40=(a65*a93);
  a101=(a101-a40);
  a40=(a73*a101);
  a85=(a85+a93);
  a85=(a85-a35);
  a40=(a40*a85);
  a98=(a102+a3);
  a100=(a73*a98);
  a109=(a66*a91);
  a99=(a65*a71);
  a109=(a109-a99);
  a99=(a74*a102);
  a109=(a109+a99);
  a100=(a100*a109);
  a40=(a40-a100);
  a100=(a73*a101);
  a93=(a66*a93);
  a35=(a65*a35);
  a93=(a93+a35);
  a100=(a100*a93);
  a40=(a40+a100);
  a100=arg[1]? arg[1][34] : 0;
  a40=(a40-a100);
  a40=(a67*a40);
  a100=(a73*a98);
  a35=(a66*a71);
  a99=(a65*a91);
  a35=(a35+a99);
  a99=(a67*a102);
  a35=(a35+a99);
  a100=(a100*a35);
  a99=(a73*a93);
  a99=(a99*a85);
  a100=(a100-a99);
  a99=(a73*a93);
  a99=(a99*a93);
  a100=(a100-a99);
  a99=(a5*a98);
  a99=(a99*a98);
  a100=(a100+a99);
  a99=arg[1]? arg[1][35] : 0;
  a100=(a100-a99);
  a100=(a74*a100);
  a40=(a40+a100);
  a100=(a73*a35);
  a100=(a100*a109);
  a99=(a73*a109);
  a99=(a99*a35);
  a100=(a100-a99);
  a99=(a73*a101);
  a99=(a99*a85);
  a100=(a100-a99);
  a99=(a11*a101);
  a99=(a99*a93);
  a100=(a100-a99);
  a93=(a73*a93);
  a93=(a93*a101);
  a100=(a100+a93);
  a109=(a5*a109);
  a109=(a109*a98);
  a100=(a100-a109);
  a109=arg[1]? arg[1][39] : 0;
  a100=(a100-a109);
  a40=(a40+a100);
  a75=(a75+a40);
  a73=(a73*a74);
  a73=(a73*a3);
  a40=(a73*a66);
  a70=(a70*a67);
  a70=(a70*a3);
  a109=(a70*a65);
  a40=(a40+a109);
  a40=(a40*a71);
  a109=(a73*a65);
  a98=(a70*a66);
  a109=(a109-a98);
  a109=(a109*a91);
  a40=(a40+a109);
  a73=(a73*a67);
  a70=(a70*a74);
  a73=(a73-a70);
  a73=(a73*a102);
  a40=(a40+a73);
  a75=(a75-a40);
  a40=1.0000000000000001e-01;
  a40=(a40*a67);
  a40=(a5*a40);
  a40=(a40+a4);
  a73=arg[1]? arg[1][3] : 0;
  a70=(a73-a100);
  a40=(a40*a70);
  a75=(a75+a40);
  a96=(a96+a75);
  a83=(a83-a96);
  a83=(a83/a34);
  a38=(a38*a83);
  a86=(a86+a38);
  a38=(a23*a72);
  a34=(a89*a22);
  a38=(a38-a34);
  a92=(a0*a92);
  a82=(a82+a92);
  a92=(a7*a82);
  a94=(a0*a94);
  a36=(a36-a94);
  a94=(a8*a36);
  a92=(a92+a94);
  a94=(a39+a10);
  a34=(a9*a94);
  a92=(a92-a34);
  a34=(a7*a97);
  a96=(a8*a95);
  a34=(a34-a96);
  a96=(a12*a103);
  a34=(a34+a96);
  a34=(a2*a34);
  a92=(a92+a34);
  a92=(a5*a92);
  a36=(a7*a36);
  a82=(a8*a82);
  a36=(a36-a82);
  a12=(a12*a94);
  a36=(a36+a12);
  a7=(a7*a95);
  a8=(a8*a97);
  a7=(a7+a8);
  a9=(a9*a103);
  a7=(a7-a9);
  a7=(a2*a7);
  a36=(a36-a7);
  a36=(a11*a36);
  a92=(a92+a36);
  a94=(a13*a94);
  a92=(a92+a94);
  a92=(a92+a107);
  a104=(a104-a92);
  a104=(a104/a13);
  a38=(a38*a104);
  a86=(a86-a38);
  a38=(a89*a61);
  a13=(a23*a49);
  a38=(a38+a13);
  a105=(a1*a105);
  a37=(a37+a105);
  a37=(a66*a37);
  a84=(a1*a84);
  a90=(a90-a84);
  a90=(a65*a90);
  a37=(a37+a90);
  a39=(a39+a83);
  a67=(a67*a39);
  a37=(a37+a67);
  a66=(a66*a91);
  a65=(a65*a71);
  a66=(a66-a65);
  a74=(a74*a102);
  a66=(a66+a74);
  a66=(a3*a66);
  a37=(a37+a66);
  a5=(a5*a37);
  a39=(a11*a39);
  a5=(a5+a39);
  a5=(a5+a100);
  a73=(a73-a5);
  a73=(a73/a11);
  a38=(a38*a73);
  a86=(a86-a38);
  a38=cos(a14);
  a11=(a16*a38);
  a14=sin(a14);
  a5=(a19*a14);
  a11=(a11-a5);
  a5=(a27*a11);
  a100=(a16*a38);
  a39=(a19*a14);
  a100=(a100-a39);
  a100=(a26*a100);
  a39=(a38-a14);
  a25=(a25*a39);
  a100=(a100+a25);
  a25=(a16*a14);
  a37=(a19*a38);
  a25=(a25+a37);
  a25=(a29*a25);
  a37=(a14+a38);
  a28=(a28*a37);
  a25=(a25+a28);
  a100=(a100-a25);
  a25=(a41*a100);
  a5=(a5-a25);
  a25=(a16*a14);
  a28=(a19*a38);
  a25=(a25+a28);
  a28=(a32*a25);
  a31=(a31*a39);
  a39=(a16*a14);
  a66=(a19*a38);
  a39=(a39+a66);
  a39=(a26*a39);
  a31=(a31-a39);
  a39=(a16*a38);
  a66=(a19*a14);
  a39=(a39-a66);
  a39=(a29*a39);
  a33=(a33*a37);
  a39=(a39-a33);
  a31=(a31-a39);
  a39=(a43*a31);
  a28=(a28+a39);
  a5=(a5-a28);
  a5=(a5*a0);
  a28=cos(a6);
  a39=(a15*a28);
  a6=sin(a6);
  a33=(a18*a6);
  a39=(a39-a33);
  a33=(a27*a39);
  a37=(a15*a28);
  a66=(a18*a6);
  a37=(a37-a66);
  a37=(a26*a37);
  a66=(a15*a6);
  a74=(a18*a28);
  a66=(a66+a74);
  a66=(a29*a66);
  a37=(a37-a66);
  a41=(a41*a37);
  a33=(a33-a41);
  a41=(a15*a6);
  a66=(a18*a28);
  a41=(a41+a66);
  a26=(a26*a41);
  a41=(a15*a28);
  a66=(a18*a6);
  a41=(a41-a66);
  a29=(a29*a41);
  a26=(a26+a29);
  a43=(a43*a26);
  a29=(a15*a6);
  a41=(a18*a28);
  a29=(a29+a41);
  a41=(a32*a29);
  a43=(a43-a41);
  a33=(a33+a43);
  a33=(a33*a2);
  a5=(a5+a33);
  a5=(a5*a0);
  a33=cos(a45);
  a43=(a48*a33);
  a45=sin(a45);
  a41=(a51*a45);
  a43=(a43-a41);
  a41=(a54*a43);
  a66=(a48*a33);
  a74=(a51*a45);
  a66=(a66-a74);
  a66=(a53*a66);
  a74=(a45+a33);
  a52=(a52*a74);
  a66=(a66-a52);
  a52=(a33-a45);
  a55=(a55*a52);
  a102=(a48*a45);
  a65=(a51*a33);
  a102=(a102+a65);
  a102=(a56*a102);
  a55=(a55-a102);
  a66=(a66-a55);
  a55=(a49*a66);
  a41=(a41+a55);
  a55=(a48*a33);
  a102=(a51*a45);
  a55=(a55-a102);
  a55=(a56*a55);
  a60=(a60*a52);
  a55=(a55+a60);
  a60=(a48*a45);
  a52=(a51*a33);
  a60=(a60+a52);
  a60=(a53*a60);
  a58=(a58*a74);
  a60=(a60+a58);
  a55=(a55-a60);
  a60=(a57*a55);
  a58=(a48*a45);
  a74=(a51*a33);
  a58=(a58+a74);
  a58=(a59*a58);
  a60=(a60-a58);
  a41=(a41+a60);
  a41=(a41*a1);
  a60=cos(a47);
  a58=(a50*a60);
  a47=sin(a47);
  a74=(a46*a47);
  a58=(a58-a74);
  a74=(a54*a58);
  a52=(a50*a60);
  a102=(a46*a47);
  a52=(a52-a102);
  a52=(a53*a52);
  a102=(a50*a47);
  a65=(a46*a60);
  a102=(a102+a65);
  a102=(a56*a102);
  a52=(a52+a102);
  a102=(a49*a52);
  a74=(a74+a102);
  a102=(a50*a60);
  a65=(a46*a47);
  a102=(a102-a65);
  a56=(a56*a102);
  a102=(a50*a47);
  a65=(a46*a60);
  a102=(a102+a65);
  a53=(a53*a102);
  a56=(a56-a53);
  a57=(a57*a56);
  a53=(a50*a47);
  a102=(a46*a60);
  a53=(a53+a102);
  a53=(a59*a53);
  a57=(a57-a53);
  a74=(a74+a57);
  a74=(a74*a3);
  a41=(a41+a74);
  a41=(a41*a1);
  a5=(a5-a41);
  a25=(a20*a25);
  a25=(a25+a11);
  a25=(a25*a0);
  a29=(a20*a29);
  a29=(a29+a39);
  a29=(a29*a2);
  a25=(a25+a29);
  a25=(a25*a2);
  a5=(a5-a25);
  a43=(a43*a1);
  a58=(a58*a3);
  a43=(a43+a58);
  a43=(a43*a3);
  a5=(a5+a43);
  a23=(a23*a5);
  a43=(a16*a14);
  a58=(a19*a38);
  a43=(a43+a58);
  a58=(a27*a43);
  a100=(a17*a100);
  a58=(a58+a100);
  a16=(a16*a38);
  a19=(a19*a14);
  a16=(a16-a19);
  a19=(a32*a16);
  a31=(a21*a31);
  a19=(a19-a31);
  a58=(a58+a19);
  a58=(a58*a0);
  a19=(a15*a6);
  a31=(a18*a28);
  a19=(a19+a31);
  a27=(a27*a19);
  a17=(a17*a37);
  a27=(a27+a17);
  a15=(a15*a28);
  a18=(a18*a6);
  a15=(a15-a18);
  a32=(a32*a15);
  a21=(a21*a26);
  a32=(a32+a21);
  a27=(a27+a32);
  a27=(a27*a2);
  a58=(a58+a27);
  a58=(a58*a0);
  a66=(a61*a66);
  a27=(a48*a45);
  a32=(a51*a33);
  a27=(a27+a32);
  a32=(a54*a27);
  a66=(a66-a32);
  a48=(a48*a33);
  a51=(a51*a45);
  a48=(a48-a51);
  a48=(a59*a48);
  a55=(a63*a55);
  a48=(a48+a55);
  a66=(a66-a48);
  a66=(a66*a1);
  a52=(a61*a52);
  a48=(a50*a47);
  a55=(a46*a60);
  a48=(a48+a55);
  a54=(a54*a48);
  a52=(a52-a54);
  a50=(a50*a60);
  a46=(a46*a47);
  a50=(a50-a46);
  a59=(a59*a50);
  a63=(a63*a56);
  a59=(a59+a63);
  a52=(a52-a59);
  a52=(a52*a3);
  a66=(a66+a52);
  a66=(a66*a1);
  a58=(a58+a66);
  a16=(a20*a16);
  a16=(a16-a43);
  a16=(a16*a0);
  a20=(a20*a15);
  a20=(a20-a19);
  a20=(a20*a2);
  a16=(a16+a20);
  a16=(a16*a2);
  a58=(a58+a16);
  a27=(a27*a1);
  a48=(a48*a3);
  a27=(a27+a48);
  a27=(a27*a3);
  a58=(a58+a27);
  a89=(a89*a58);
  a23=(a23-a89);
  a86=(a86-a23);
  if (res[0]!=0) res[0][4]=a86;
  a86=(a69*a88);
  a23=(a68*a78);
  a86=(a86+a23);
  a23=(a86*a62);
  a69=(a69*a44);
  a68=(a68*a87);
  a69=(a69-a68);
  a68=(a69*a24);
  a23=(a23+a68);
  a23=(a4+a23);
  a23=(a23*a83);
  a68=(a86*a30);
  a89=(a69*a42);
  a68=(a68+a89);
  a68=(a68*a10);
  a23=(a23-a68);
  a68=(a69*a72);
  a89=(a86*a22);
  a68=(a68-a89);
  a68=(a68*a104);
  a23=(a23-a68);
  a68=(a86*a61);
  a89=(a69*a49);
  a68=(a68+a89);
  a68=(a68*a73);
  a23=(a23-a68);
  a69=(a69*a5);
  a86=(a86*a58);
  a69=(a69-a86);
  a23=(a23-a69);
  if (res[0]!=0) res[0][5]=a23;
  a23=(a76*a88);
  a69=(a80*a78);
  a23=(a23-a69);
  a69=(a23*a62);
  a76=(a76*a44);
  a80=(a80*a87);
  a76=(a76+a80);
  a80=(a76*a24);
  a69=(a69+a80);
  a69=(a69*a83);
  a80=(a23*a30);
  a86=(a76*a42);
  a80=(a80+a86);
  a80=(a80*a10);
  a69=(a69-a80);
  a80=(a76*a72);
  a86=(a23*a22);
  a80=(a80-a86);
  a80=(a4-a80);
  a80=(a80*a104);
  a69=(a69+a80);
  a80=(a23*a61);
  a86=(a76*a49);
  a80=(a80+a86);
  a80=(a80*a73);
  a69=(a69-a80);
  a76=(a76*a5);
  a23=(a23*a58);
  a76=(a76-a23);
  a69=(a69-a76);
  if (res[0]!=0) res[0][6]=a69;
  a87=(a81*a87);
  a44=(a77*a44);
  a87=(a87-a44);
  a49=(a87*a49);
  a77=(a77*a88);
  a81=(a81*a78);
  a77=(a77+a81);
  a61=(a77*a61);
  a49=(a49-a61);
  a4=(a4-a49);
  a4=(a4*a73);
  a42=(a87*a42);
  a30=(a77*a30);
  a42=(a42-a30);
  a42=(a42*a10);
  a62=(a77*a62);
  a24=(a87*a24);
  a62=(a62-a24);
  a62=(a62*a83);
  a42=(a42+a62);
  a22=(a77*a22);
  a72=(a87*a72);
  a22=(a22+a72);
  a22=(a22*a104);
  a42=(a42+a22);
  a4=(a4-a42);
  a77=(a77*a58);
  a87=(a87*a5);
  a77=(a77+a87);
  a4=(a4-a77);
  if (res[0]!=0) res[0][7]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int xdot(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int xdot_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int xdot_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void xdot_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int xdot_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void xdot_release(int mem) {
}

CASADI_SYMBOL_EXPORT void xdot_incref(void) {
}

CASADI_SYMBOL_EXPORT void xdot_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int xdot_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int xdot_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real xdot_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* xdot_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* xdot_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* xdot_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* xdot_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int xdot_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_xdot(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  int mem;
  casadi_real w[167];
  casadi_int *iw = 0;
  const casadi_real* arg[2] = {0};
  casadi_real* res[1] = {0};
  if (argc>2) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"xdot\" failed. Too many input arguments (%d, max 2)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"xdot\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+56);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+8, casadi_s1, w+56);
  --resc;
  res[0] = w+48;
  xdot_incref();
  mem = xdot_checkout();
  i = xdot(arg, res, iw, w+56, mem);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"xdot\" failed.");
  xdot_release(mem);
  xdot_decref();
  if (res[0]) resv[0] = casadi_to_mex(casadi_s0, res[0]);
}
#endif


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[5];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_xdot(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "xdot")==0) {
    mex_xdot(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'xdot'");
}
#endif
#ifdef __cplusplus
} /* extern "C" */
#endif
